repository: sproogen/resume-theme
favicon: images/favicon.ico

version: 2

name: Sina Roomi
title: UMBC Sophomore
email: sroomi2004@gmail.com
phone: 443-613-0301


darkmode: true


github_username:  s-roomi

linkedin_username: sina-roomi-b16289252


additional_links:
- title: Resume
  icon: fas fa-file
  url: https://drive.google.com/file/d/1e5oBHDvGU4tk_gLgZ6igBVCsN_kq8VwV/view?usp=sharing


about_profile_image: images/sinaroomi.jpg
about_content: |
  Hey. I'm Sina, a sophomore at UMBC majoring in computer science. My world revolves around coding challenges, exploring the latest tech trends, and turning lines of code into endless possibilities! 
  
  Currently on a mission to:

    Secure an exciting internship to apply and expand my skills in real-world scenarios. 

  
    Dive into creating cool projects that not only showcase my abilities but also make a positive impact.
  
  I am most skilled in: <mark>C++</mark>, <mark>Python</mark>

content:
  - title: Education
    layout: list 
    content:
      - layout: left
        title: University of Maryland, Baltimore County
        caption: 2022 - 2026
        sub_title: Computer Science
        quote: >
          Founded in 1966, UMBC stands as a prominent higher education institution, recognized for its impact, reputation, and academic excellence, not only in the United States but also on a global scale.
        description: |
          In my two years at UMBC, I gained valuable skills from a variety of courses—improving my time management, honing problem-solving abilities, and refining my communication skills. My time at UMBC has been fulfilling, and I'm excited about the ongoing journey of learning and growth ahead.

  - title: Projects
    layout: list 
    content:
      - layout: top-middle
        title: Projects
        link: github.com/s-roomi
        additional_links:
          - title:  github_page
            icon: fab fa-github
            url: github.com/S-Roomi?tab=repositories
        description: |
          For a comprehensive view of my projects, please feel free to explore the associated GitHub repositories. Click on the GitHub link or icon to access detailed information and delve into the work I've undertaken.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Dulaney Highschool Tech Intern
        caption: September 2020 - May 2022
        description: | 
            Throughout my role as a technical intern, I demonstrated proficiency in diagnosing and resolving issues across a spectrum of devices, encompassing laptops, desktops, projectors, printers, and diverse technological assets. In addition to this, I took on the responsibility of re-imaging devices to optimize their performance. Providing adept technical support to students, I ensured efficient resolution of their queries and concerns.

            In a proactive capacity, I endeavored to enhance operational efficiency by implementing automation solutions. This encompassed automating routine tasks, such as email communications, and simplifying troubleshooting procedures for common computer issues. 

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interest in computer science, some of my other interests and hobbies are:
      - Reading
      - Gaming
      - Lifting
      - Longboarding


footer_show_references: true


remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
