# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sina Roomi
title: UMBC Sophomore
email: sroomi2004@gmail.com
phone: 443-613-0301
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  s-roomi
linkedin_username: sina-roomi-b16289252

# Additional icon links
#additional_links:
- title: itsgoingto.be
  icon: fa-solid fa-file
  url: https://docs.google.com/document/d/19WEYCcTeb9DDMN_qrUIqjkyirpxgOH5F/edit?usp=sharing&ouid=106267943771617935005&rtpof=true&sd=true
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey, I'm Sina, a sophomore at UMBC majoring in computer science. My world revolves around coding challenges, exploring the latest tech trends, and turning lines of code into endless possibilities! 
  
  Currently on a mission to:

  🌐 Secure an exciting internship to apply and expand my skills in real-world scenarios. 

  
  💡 Dive into creating cool projects that not only showcase my abilities but also make a positive impact.
  
  I am most skilled in: <mark>C++</mark>, <mark>Python</mark>, and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Projects
        link: github.com/s-roomi
        # link_text: Project Website
        additional_links:
          - title:  github_page
            icon: fab fa-github
            url: github.com/S-Roomi?tab=repositories
        description: | # this will include new lines to allow paragraphs
          For a comprehensive view of my projects, please feel free to explore the associated GitHub repositories. Click on the GitHub link or icon to access detailed information and delve into the work I've undertaken.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Maryland, Baltimore County
        caption: 2022 - 2026
        sub_title: Computer Science
        quote: >
          Founded in 1966, UMBC stands as a prominent higher education institution, recognized for its impact, reputation, and academic excellence, not only in the United States but also on a global scale.
        description: | # this will include new lines to allow paragraphs
          .

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interest in computer science, some of my other interests and hobbies are:
      - Hiking
      - Gaming
      - Lifting
      - [Longboarding](https://www.youtube.com/watch?v=eQw-cPOAZ98)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
